### PR TITLE
Illustrate testing with Docker image of Rabbit MQ

### PR DESCRIPTION
**Pull request by jonmat**
---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by mookid8000** [comment]
It seems like NuGet package restore refuses to resolve the Rebus version versions because the test project depends on 4.0.1 while the driver depends on 4.0.0.

Could you maybe try and consolidate the version by running

    update-package rebus -version 4.0.1

in the package manager console?

**Comment by jonmat** [comment]
yes, done.

**Comment by mookid8000** [comment]
Interesting! I wish Docker worked on my Windows VM so I could try it.... 😞

**Comment by mookid8000** [comment]
I get this silly error message:

image

**Comment by mookid8000** [comment]
ah, turned out that I just needed to enable this:

image

Figured it out when I saw that "Hyper-V Hypervisor" was grayed out in "Turn Windows features on/off"

**Pull request merged**
