### PR TITLE
Added functionality to automatically restore deleted queues and their subscriptions

### PR DESCRIPTION
**Pull request by pjh1974**
@mookid8000 This PR is related to an issue I raised earlier.  This is the best solution that I have found, I can't think of any side-effects that it will cause but in my particular case solves the problem perfectly.
---
Rebus is [MIT-licensed](https://opensource.org/licenses/MIT). The code submitted in this pull request needs to carry the MIT license too. By leaving this text in, __I hereby acknowledge that the code submitted in the pull request has the MIT license and can be merged with the Rebus codebase__.

### CODE REVIEW

**Comment by mookid8000** [comment]
Cool! Could you maybe go click the CLA thing above, so I can accept your pull request?

**Comment by pjh1974** [comment]
@mookid8000 I've already clicked the CLA think several times, it says thank you for signing the CLA and sends me back to GitHub but it seems GitHub is not detecting the signature from the CLA assistant.  I've just tried it again and it's still doing the same thing.

**Comment by mookid8000** [comment]
I think it's because your commits have been made with an email address unknown to GitHub. This also shows because your name "Peter Holmes" on the commits is not clickable.

Under your GitHub user account, you can add several email addresses, so you should probably go and add yours there.

**Comment by pjh1974** [comment]
@mookid8000 Finally sorted it.  Thanks.

**Comment by mookid8000** [comment]
Perfect 😁

**Comment by mookid8000** [comment]
it'll be out in 5.0.0-b02 in a few minutes

**Comment by pjh1974** [comment]
Thanks @mookid8000, I had to add my work email address.  I think it is because I use my work email address for the Git client, but my personal email address for GitHub.

**Pull request merged**
